Part 1: Data Exploration with Pandas (30 Points)


Loading csv file using pandas, and doing some data analysis by using the pandas inbuilt functions, also saving all the changes made to a newfile in csv format

In [20]:
import pandas as pd


In [ ]:
df = pd.read_csv('/content/sample_data/california_housing_train.csv')

In [ ]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

In [ ]:
df.tail(10)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16990    -124.22     41.73                28.0       3003.0           699.0   
16991    -124.23     41.75                11.0       3159.0           616.0   
16992    -124.23     40.81                52.0       1112.0           209.0   
16993    -124.23     40.54                52.0       2694.0           453.0   
16994    -124.25     40.28                32.0       1430.0           419.0   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
16990      1530.0       653.0         1.7038             78300.0  
16991      1343.0       479.0         2.4805             73200.0  
16992       544.0       172.0         3.3462             50800.0  
16993      1152.0       435.0         3.0806            106700.0  
16994       434.0       187.0         1.9417             76100.0  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0

In [ ]:
df.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

In [ ]:
df["total_bedrooms"].unique()

array([1283., 1901.,  174., ..., 1637., 1308.,  936.])

In [ ]:
df['total_bedrooms_per_total_rooms']= df['total_bedrooms'] /df['total_rooms']

In [ ]:
df['total_bedrooms_per_total_rooms']

0        0.228617
1        0.248497
2        0.241667
3        0.224517
4        0.224209
           ...   
16995    0.177718
16996    0.224777
16997    0.198356
16998    0.206587
16999    0.164835
Name: total_bedrooms_per_total_rooms, Length: 17000, dtype: float64

In [ ]:
df['total_bedrooms_per_total_rooms'].mean()

0.21275998821034803

In [ ]:
df['total_bedrooms_per_total_rooms'].std()

0.057823008903161756

In [ ]:
df[df['median_income'] > 5]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
32       -115.39     32.76                16.0       1136.0           196.0   
69       -115.55     32.98                33.0       2266.0           365.0   
92       -115.57     32.78                20.0       1534.0           235.0   
98       -115.58     32.78                 5.0       2494.0           414.0   
100      -115.59     32.79                 8.0       2183.0           307.0   
...          ...       ...                 ...          ...             ...   
16737    -122.89     38.38                16.0       2017.0           369.0   
16762    -122.94     38.57                33.0       1530.0           266.0   
16776    -123.00     38.33                 8.0       3223.0           637.0   
16802    -123.17     39.18                14.0       2240.0           327.0   
16899    -124.05     40.94                14.0       1452.0           217.0   

       population  households  median_income  median_house_value  \
32          481.0       185.0         6.2558            146300.0   
69          952.0       360.0         5.4349            143000.0   
92          871.0       222.0         6.2715             97200.0   
98         1416.0       421.0         5.7843            110100.0   
100        1000.0       287.0         6.3814            159900.0   
...           ...         ...            ...                 ...   
16737       931.0       336.0         5.7664            267500.0   
16762       728.0       250.0         5.1005            266700.0   
16776       851.0       418.0         5.6445            364800.0   
16802      1030.0       308.0         5.9585            214900.0   
16899       516.0       181.0         5.0329            165600.0   

       total_bedrooms_per_total_rooms  
32                           0.172535  
69                           0.161077  
92                           0.153194  
98                           0.165998  
100                          0.140632  
...                               ...  
16737                        0.182945  
16762                        0.173856  
16776                        0.197642  
16802                        0.145982  
16899                        0.149449  

[3752 rows x 10 columns]

In [ ]:
df[df['median_income'] > 5].count()

longitude                         3752
latitude                          3752
housing_median_age                3752
total_rooms                       3752
total_bedrooms                    3752
population                        3752
households                        3752
median_income                     3752
median_house_value                3752
total_bedrooms_per_total_rooms    3752
dtype: int64

In [ ]:
df[(df['total_rooms'] > 10000) & (df['median_house_value'] < 150000)]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
133      -116.06     34.15                15.0      10377.0          2331.0   
191      -116.36     33.88                11.0      12557.0          3098.0   
198      -116.38     33.73                10.0      11836.0          2405.0   
201      -116.39     33.82                15.0      11115.0          2257.0   
229      -116.47     33.81                 7.0      10105.0          2481.0   
...          ...       ...                 ...          ...             ...   
12654    -121.75     38.67                 9.0      12139.0          2640.0   
12772    -121.79     36.64                11.0      32627.0          6445.0   
13388    -121.94     38.27                35.0      10869.0          2226.0   
13707    -122.00     38.25                 7.0      11768.0          1893.0   
15436    -122.31     40.55                11.0      13714.0          2302.0   

       population  households  median_income  median_house_value  \
133        4507.0      1807.0         2.2466             66800.0   
191        2453.0      1232.0         1.7844             78500.0   
198        3811.0      1570.0         4.0079            134500.0   
201        4122.0      1653.0         2.7219             74400.0   
229        6274.0      2095.0         2.4497             90900.0   
...           ...         ...            ...                 ...   
12654      6837.0      2358.0         3.1250            132500.0   
12772     28566.0      6082.0         2.3087            118800.0   
13388      9879.0      2152.0         2.5681             81300.0   
13707      6657.0      1874.0         4.9222            142900.0   
15436      6511.0      2267.0         3.5522            100100.0   

       total_bedrooms_per_total_rooms  
133                          0.224631  
191                          0.246715  
198                          0.203194  
201                          0.203059  
229                          0.245522  
...                               ...  
12654                        0.217481  
12772                        0.197536  
13388                        0.204803  
13707                        0.160860  
15436                        0.167858  

[67 rows x 10 columns]

In [ ]:
df2=df.copy()

In [ ]:
df2.to_csv('newfile.csv')

Part 2: Numerical Analysis with NumPy (30 Points)


importing numpy and using its operations and inbuilt functions to understand arrays and some basic functions.

In [ ]:
import numpy as np


In [ ]:
arr = np.arange(1,21)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
even = arr[1:20:2]

In [ ]:
even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arb = np.random.randint( 10,100, size=(5,4))

In [ ]:
arb

array([[34, 65, 49, 71],
       [13, 31, 82, 86],
       [91, 50, 47, 13],
       [43, 66, 69, 43],
       [28, 30, 50, 72]])

In [ ]:
arb[0:3,0:2]

array([[34, 65],
       [13, 31],
       [91, 50]])

In [ ]:
arr2 = arr.reshape([4,5])

In [ ]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
arr3 = arr2.flatten()

In [ ]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
abc = np.ones([5,4])

In [ ]:
abc


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
np.dot(arr2,abc)

array([[15., 15., 15., 15.],
       [40., 40., 40., 40.],
       [65., 65., 65., 65.],
       [90., 90., 90., 90.]])

In [ ]:
aray = np.random.randint(0, 100, 50)

In [ ]:
aray

array([36, 31,  0, 33, 82, 24, 92,  3, 62, 32, 10, 98, 95, 74, 63, 58, 81,
       10, 11,  3, 35, 82, 17, 65,  1, 52,  9, 57, 51, 90, 58, 76, 45, 42,
       63, 48,  4, 86, 33, 59, 64,  9, 21, 12, 98, 49, 60, 89, 68, 67])

In [ ]:
aray[aray>50]

array([82, 92, 62, 98, 95, 74, 63, 58, 81, 82, 65, 52, 57, 51, 90, 58, 76,
       63, 86, 59, 64, 98, 60, 89, 68, 67])

In [ ]:
print(aray[[3,5]]) # fancy indexing

[33 24]


In [ ]:
mean = arr2.mean(axis=0)
print (mean)

[ 8.5  9.5 10.5 11.5 12.5]


In [ ]:
print(arr2.max(axis=0))

[16 17 18 19 20]


In [ ]:
print(arr2.sum(axis=0))

[34 38 42 46 50]


In [ ]:
mask = arr2 >mean
arr2[mask]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

Part 3: Problem Solving with Python Basics (20 Points)

Learnt fibonacci sequence and how to use the for loop to write the code. Also learnt how to take user inputs and exception handling

In [ ]:
a=0
b=1
for i in range(100):
  if(i==0) :
    print(0)
  elif(i==1):
    print(1)
  else:
    num=a+b
    a=b
    b=num
    print(num)

0
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181
6765
10946
17711
28657
46368
75025
121393
196418
317811
514229
832040
1346269
2178309
3524578
5702887
9227465
14930352
24157817
39088169
63245986
102334155
165580141
267914296
433494437
701408733
1134903170
1836311903
2971215073
4807526976
7778742049
12586269025
20365011074
32951280099
53316291173
86267571272
139583862445
225851433717
365435296162
591286729879
956722026041
1548008755920
2504730781961
4052739537881
6557470319842
10610209857723
17167680177565
27777890035288
44945570212853
72723460248141
117669030460994
190392490709135
308061521170129
498454011879264
806515533049393
1304969544928657
2111485077978050
3416454622906707
5527939700884757
8944394323791464
14472334024676221
23416728348467685
37889062373143906
61305790721611591
99194853094755497
160500643816367088
259695496911122585
420196140727489673
679891637638612258
1100087778366101931
1779979416004714189
2880067194370816120
4660046610375530309
754011380474634642

In [10]:
for num in range(1,50):
  if num % 3 == 0:
    print("Fizz")
  elif num % 5 == 0:
    print("Buzz")
  elif num % 3 == 0 and num % 5 == 0:
    print("FizzBuzz")
  else:
    print(num)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
Fizz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
Fizz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
Fizz
46
47
Fizz
49


In [14]:
inp = eval(input("Enter the list"))
n=len(inp)
inp.sort()
if n%2==0: #this is evem
  median1 = inp[n//2]
  median2 = inp[n//2 - 1] # n starting from 0
  median = (median1 + median2)/2 #average of two medians
else:
  median = inp[n//2]
print(median)


Enter the list[1,2,3,5,4,6]
3.5


In [16]:
inp = eval(input("enter the number of arguments : "))
sum=0
for i in range (inp):
  num = int(input("enter the number : "))
  sum=sum+num

avg=sum/inp
print(avg)

enter the number of arguments : 4
enter the number : 0
enter the number : 1
enter the number : 2
enter the number : 3
1.5


In [19]:
a= int(input("enter the number : "))

b= int(input("enter the number : "))
try:
  c=a/b
except ZeroDivisionError:
   print("Division by zero , hence not defined")

enter the number : 6
enter the number : 0
Division by zero , hence not defined
